---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: src/posts
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - post
- type: heading
  label: Doula Page
- type: document
  path: src/doula/about.md
  label: About
- type: directory
  path: src/faqs
  label: FAQs
  create: documents
  match: "**/*"
  templates:
  - faqs
- type: directory
  path: src/testimonials
  label: Testimonials
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/static/uploads"
front_matter_path: ".forestry/front_matter/templates"
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
